# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test111():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_111(self):
    self.driver.get("https://ceshiren.com/")
    self.driver.set_window_size(1550, 838)
    self.driver.find_element(By.LINK_TEXT, "金羽毛奖-活动详情").click()
    time.sleep(2)
    self.driver.refresh()
    time.sleep(2)
    self.driver.minimize_window()
    time.sleep(2)
    self.driver.maximize_window()
    time.sleep(2)
    self.driver.back()
    time.sleep(2)

  
